### ISSUE TITLE
Task: Linked List Proposal

### ISSUE THREAD

**Issue by massimovignelli** [kaentor/LinkedList#4]
#### Key

> Id: **KAEN-4**
Project: [**LinkedList · Product**](https://github.com/kaentor/LinkedList/projects/1)

#### Description

For Kæntor, I need a Linked List proposal to establish all the features that will be implemented.

#### Task Checklist

- [x] Create a README.md file.
- [x] List all the possible features.
- [x] Write the needed additional notes.

#### Assignees

- [x] Final assign @kyoeuler

**Comment by massimovignelli** [comment]
I’ll start the development of this feature.

**Comment by massimovignelli** [comment]
Review was done successfully.

**Comment by massimovignelli** [comment]
I’m closing this issue. Please, see:

- [x] [v0.2.0-alpha.1 – Task4/Linked List Proposal _Pull Request_](https://github.com/kaentor/LinkedList/pull/9)
