### ISSUE TITLE
Task: Linked List Repository

### ISSUE THREAD

**Issue by massimovignelli** [kaentor/LinkedList#5]
#### Key

> Id: **KAEN-5**
Project: [**LinkedList · Product**](https://github.com/kaentor/LinkedList/projects/1)

#### Description

Create the Linked List as a separated module in GitHub organization.

#### Task Checklist

- [ ] Create the repository `LinkedList`.
- [ ] Add the build setup.
- [ ] Write the first implementation of a Linked List.

#### Assignees

- [x] Final assign @kyoeuler

**Comment by massimovignelli** [comment]
I’ll start the development of this feature.

###### More details at: [JIRA/Task KAEN-3](https://kyoeuler.atlassian.net/browse/KAEN-5?atlOrigin=eyJpIjoiMjQzMzUzYTAzMzVjNDQ4NGJjYmY3YWVlMjJkOGQ5NDgiLCJwIjoiaiJ9)

**Comment by massimovignelli** [comment]
Review was done successfully.

**Comment by massimovignelli** [comment]
I’m closing this issue. Please, see:

- [x] [v0.1.0-alpha.1 – Task5/Setup Configuration _Pull Request_](https://github.com/kaentor/LinkedList/pull/8)
