### ISSUE TITLE
Task: Linked List Source Code

### ISSUE THREAD

**Issue by massimovignelli** [kaentor/LinkedList#6]
#### Key

> Id: **KAEN-6**
Project: [**LinkedList · Product**](https://github.com/kaentor/LinkedList/projects/1)

#### Description

Create the _source code_ and _tests_ for the Linked List implementation.

#### Task Checklist

- [ ] Create the foundation code for the Linked List.
- [ ] Create the source code and tests for:
  - [ ] Insert a new node
  - [ ] Remove a node
  - [ ] Find/Search a node
  - [ ] Replace a node

#### Assignees

- [x] Final assign @kyoeuler

**Comment by massimovignelli** [comment]
This _Feature_ is currently active.

###### More details at: [JIRA/Task KAEN-6](https://kyoeuler.atlassian.net/browse/KAEN-6?atlOrigin=eyJpIjoiZTFhYjBmNTllMzA3NDcxYjk0MjZkZDk4N2ZmYzZlMTciLCJwIjoiaiJ9)
