### ISSUE TITLE
Task: Linked List Documentation

### ISSUE THREAD

**Issue by massimovignelli** [kaentor/LinkedList#7]
#### Key

> Id: **KAEN-7**
Project: [**LinkedList · Product**](https://github.com/kaentor/LinkedList/projects/1)

#### Description

Add the related comments, documentation, tutorials and publish the package.

#### Task Checklist

- [ ] Add comments in the source code.
- [ ] Add the corresponding Linked List documentation.
- [ ] Show the full API available.
- [ ] Publish the package.

#### Assignees

- [x] Final assign @kyoeuler
